yolo_model:

  config_file:
    name: yolov3-tiny-trees.cfg
  weight_file:
    name: yolov3-tiny-trees_2000.weights
  threshold:
    value: 0.8
  detection_classes:
    names:
      - tree1
      - tree2
      - tree3
